#!/bin/bash
#Script permettant de supprimer les enregistrementsnayant le même titre vieux d'une semaine

#Variable
f=$1
title=$2
name=$(basename "$f" .ts)

find "/share/video/enregistrement/$title" -name "*" -mtime +6 -exec rm {} \;
